version: "2.0"

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=ruleval
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

  validationhg-app:
    image: febi/validationhg
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
    ports:
      - 80:8080
